name: Java CI with Maven

# A pipeline será disparada a cada 'push' ou 'pull request' na branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Roda em uma máquina virtual Linux atualizada cedida pelo GitHub
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Baixa o código do seu repositório para a máquina virtual
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Instala e configura o Java 17 na máquina do GitHub
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven # Guarda as dependências em cache para os próximos builds serem mais rápidos

    # Passo 3: Compila o projeto e roda os testes (Gera o arquivo .jar)
    - name: Build with Maven
      run: mvn clean package

    # Passo 4: (Preparação para a Fase 2/4) - Simula o Build da imagem Docker
    - name: Test Docker Build Build
      run: |
        docker build -t todo-api-test .
